name: Tests with report

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install allure-behave

    - name: Run Tests with Behave
      run: |
        mkdir reports
        behave -f allure_behave.formatter:AllureFormatter -o reports/ features/

    - name: Generate Allure Report
      run: |
        allure generate reports/ -o allure-report/ --clean

    - name: Upload Test Results (Artifacts)
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report/
