name: Tests with report

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install allure-behave

    - name: Install Allure
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Install Allure CLI
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.20.1/allure-2.20.1.tgz
        tar -xvzf allure-2.20.1.tgz
        sudo mv allure-2.20.1 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

    - name: Run Tests with Behave
      run: |
        mkdir reports
        behave -f allure_behave.formatter:AllureFormatter -o reports/ features/ || true

    - name: Generate Allure Report
      run: |
        allure generate reports/ -o allure-report/ --clean

    - name: Upload Test Results (Artifacts)
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report/
